name=GTNHLib
version=${version}
additionalVersions=
className=com.gtnewhorizon.gtnhlib.core.rfb.GTNHLibRfbPlugin
transformerExclusions=com.gtnewhorizon.gtnhlib.core.shared;com.gtnewhorizon.gtnhlib.asm
versionConstraints=
loadBefore=
loadAfter=
loadRequires=
